version: '3.9'

services:
  postgresql:
    image: postgres:latest
    hostname: db
    networks:
      - net_service
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: todoapi
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - .docker:/var/lib/postgresql/data

  app:
    image: cosmtrek/air:v1.28.0
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
    depends_on:
      - postgresql
    networks:
      - net_service

networks:
  net_service:
    driver: bridge