version: '3.9'

services:
  mysql:
    image: mysql:8.1.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_DATABASE: 'todoapi'
    ports:
      - '3306:3306'
    volumes:
      - .docker/mysql:/var/lib/mysql

  app:
    image: cosmtrek/air:v1.28.0
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
    depends_on:
      - mysql