version: '3.9'

services:
  app:
    image: cosmtrek/air:v1.28.0
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
    depends_on:
      - db
  db:
    image: postgres:15.2
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: todoapi
      TZ: America/Sao_Paulo