POST http://localhost:3000/users HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
  "name": "xabrau",
  "email": "katiau@vaiwilson.com",
  "password": "10203040"
}

###

PUT http://localhost:3000/users/d08422c2-9ebb-4712-af08-d31133b824e9 HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
"name": "ronaldinho",
"email": "testeeeeee@testeeeeeeeeeeee.com",
"password": "10203040"
}

###